services:
  - type: web
    name: ton618-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
